---
opnform_project_dir: /opt/opnform
opnform_release_dir: /opt/opnform/releases
opnform_compose_file: /opt/opnform/current/docker-compose.yml
opnform_maintenance_file: /etc/caddy/opnform-maintenance.caddy
opnform_caddy_config_path: /etc/caddy/Caddyfile
opnform_caddy_service_name: caddy
opnform_caddy_custom_binary: /usr/local/bin/caddy-opnform
opnform_caddy_dns_api_token: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_DNS_API_TOKEN', default='') }}"
opnform_release_id: ''
opnform_rollback_release: ''
